# -*- coding: utf-8 -*-
"""Capstone_pyd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gA1KMgTlYh-LHNGEcRu6-Z7BjKX6b96p
"""

#라이브러리 불러오기
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#한글 폰트 조정
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

#데이터확인
accident= pd.read_csv('/content/accidentInfo.csv')
accident

#코드 분석
accident.info()

# 폰트 설정
plt.rc('font', family='NanumGothic')

# "동" 추출
accident['동'] = accident['시군구'].apply(lambda x: x.split()[-1])

# 동대문구에서 각 동별로 사고 횟수 계산
accidents_by_dong = accident['동'].value_counts()

# 시각화
plt.figure(figsize=(10, 6))
accidents_by_dong.plot(kind='bar', color='skyblue')
plt.title('동대문구 각 동별 교통사고 횟수')
plt.xlabel('동')
plt.ylabel('사고 횟수')
plt.show()

# 동대문구에서 각 동별로 사고 횟수 계산
accidents_by_dong = accident['동'].value_counts().reset_index()

accident_sum_df = pd.DataFrame(accidents_by_dong)
accident_sum_df.rename(columns={'index':'법정동', '동':'사고횟수'}, inplace =True)
accident_sum_df

# GeoJSON 파일 로드
seoul_geojson = '/content/hangjeongdong_서울특별시.geojson'
geo_data = gpd.read_file(seoul_geojson)

# 동대문구의 GeoDataFrame
dongdaemun_gdf = geo_data[geo_data['sggnm'] == '동대문구']

# GeoDataFrame 생성
geometry_data = {
    '법정동': ['제기동', '장안동', '용두동', '전농동', '답십리동', '휘경동', '청량리동', '이문동', '신설동', '회기동'],
    'latitude': [37.584134, 37.570749, 37.576328, 37.579797, 37.569883, 37.589592, 37.586643, 37.598851, 37.575204, 37.591447],
    'longitude': [127.037960, 127.068233, 127.034621, 127.053848, 127.056757, 127.061228, 127.044621, 127.062465, 127.026023, 127.051971],
    '사고횟수': [84, 73, 55, 40, 31, 25, 21, 21, 13, 10],
}

gdf = gpd.GeoDataFrame(geometry_data, geometry=gpd.points_from_xy(geometry_data['longitude'], geometry_data['latitude']), crs="EPSG:4326")

# 지도 생성
dong_map = folium.Map(location=[37.580412, 127.050155], zoom_start=14)

# 동대문구 지도에 동 별로 사고 횟수 마커 추가
for idx, row in gdf.iterrows():
    dong_name = row['법정동']  # 법정동의 이름
    accidents_count = row['사고횟수']  # 해당 법정동의 사고 횟수

    # 마커 추가
    folium.Marker([row['latitude'], row['longitude']],
                  popup=f"{dong_name}<br>사고 횟수: {accidents_count}").add_to(dong_map)

# 동대문구 경계 GeoJson 추가
for idx, row in dongdaemun_gdf.iterrows():
    folium.GeoJson(row['geometry']).add_to(dong_map)

# 지도 출력
dong_map